// This file is auto-generated by @hey-api/openapi-ts

export const AssetMedecinPublicSchema = {
    properties: {
        type_asset: {
            '$ref': '#/components/schemas/TypeAsset'
        },
        chemin_fichier: {
            type: 'string',
            maxLength: 500,
            title: 'Chemin Fichier'
        },
        est_par_defaut: {
            type: 'boolean',
            title: 'Est Par Defaut',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        medecin_id: {
            type: 'string',
            format: 'uuid',
            title: 'Medecin Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['type_asset', 'chemin_fichier', 'id', 'medecin_id'],
    title: 'AssetMedecinPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_medecins_upload_assetSchema = {
    properties: {
        type_asset: {
            '$ref': '#/components/schemas/TypeAsset'
        },
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        },
        est_par_defaut: {
            type: 'boolean',
            title: 'Est Par Defaut',
            default: false
        }
    },
    type: 'object',
    required: ['type_asset', 'file'],
    title: 'Body_medecins-upload_asset'
} as const;

export const Body_templates_upload_templateSchema = {
    properties: {
        nom_template: {
            type: 'string',
            title: 'Nom Template'
        },
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['nom_template', 'file'],
    title: 'Body_templates-upload_template'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OrdonnanceCreateSchema = {
    properties: {
        patient_id: {
            type: 'string',
            format: 'uuid',
            title: 'Patient Id'
        },
        template_id: {
            type: 'string',
            format: 'uuid',
            title: 'Template Id'
        }
    },
    type: 'object',
    required: ['patient_id', 'template_id'],
    title: 'OrdonnanceCreate'
} as const;

export const OrdonnanceGenerateRequestSchema = {
    properties: {
        html_content: {
            type: 'string',
            title: 'Html Content'
        },
        patient_id: {
            type: 'string',
            format: 'uuid',
            title: 'Patient Id'
        },
        template_id: {
            type: 'string',
            format: 'uuid',
            title: 'Template Id'
        },
        paper_size: {
            type: 'string',
            title: 'Paper Size',
            default: 'A4'
        }
    },
    type: 'object',
    required: ['html_content', 'patient_id', 'template_id'],
    title: 'OrdonnanceGenerateRequest'
} as const;

export const OrdonnancePublicSchema = {
    properties: {
        pdf_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pdf Name'
        },
        docx_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Docx Name'
        },
        statut: {
            '$ref': '#/components/schemas/StatutOrdonnance',
            default: 'brouillon'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        medecin_id: {
            type: 'string',
            format: 'uuid',
            title: 'Medecin Id'
        },
        patient_id: {
            type: 'string',
            format: 'uuid',
            title: 'Patient Id'
        },
        template_id: {
            type: 'string',
            format: 'uuid',
            title: 'Template Id'
        },
        date_emission: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Emission'
        },
        date_signature: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Signature'
        },
        lien_token: {
            type: 'string',
            title: 'Lien Token'
        }
    },
    type: 'object',
    required: ['id', 'medecin_id', 'patient_id', 'template_id', 'lien_token'],
    title: 'OrdonnancePublic'
} as const;

export const OrdonnanceTemplatePublicSchema = {
    properties: {
        nom_template: {
            type: 'string',
            maxLength: 255,
            title: 'Nom Template'
        },
        chemin_fichier_docx: {
            type: 'string',
            maxLength: 500,
            title: 'Chemin Fichier Docx'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        medecin_id: {
            type: 'string',
            format: 'uuid',
            title: 'Medecin Id'
        },
        date_upload: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Upload'
        }
    },
    type: 'object',
    required: ['nom_template', 'chemin_fichier_docx', 'id', 'medecin_id'],
    title: 'OrdonnanceTemplatePublic'
} as const;

export const OrdonnancesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OrdonnancePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'OrdonnancesPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProfilMedecinCreateSchema = {
    properties: {
        numero_ordre: {
            type: 'string',
            maxLength: 64,
            title: 'Numero Ordre'
        },
        specialite: {
            type: 'string',
            maxLength: 255,
            title: 'Specialite'
        },
        pays_exercice: {
            type: 'string',
            maxLength: 100,
            title: 'Pays Exercice'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        est_verifie: {
            type: 'boolean',
            title: 'Est Verifie',
            default: false
        }
    },
    type: 'object',
    required: ['numero_ordre', 'specialite', 'pays_exercice'],
    title: 'ProfilMedecinCreate'
} as const;

export const ProfilMedecinPublicSchema = {
    properties: {
        numero_ordre: {
            type: 'string',
            maxLength: 64,
            title: 'Numero Ordre'
        },
        specialite: {
            type: 'string',
            maxLength: 255,
            title: 'Specialite'
        },
        pays_exercice: {
            type: 'string',
            maxLength: 100,
            title: 'Pays Exercice'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        est_verifie: {
            type: 'boolean',
            title: 'Est Verifie',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['numero_ordre', 'specialite', 'pays_exercice', 'id', 'user_id'],
    title: 'ProfilMedecinPublic'
} as const;

export const ProfilMedecinUpdateSchema = {
    properties: {
        specialite: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specialite'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        est_verifie: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Est Verifie'
        }
    },
    type: 'object',
    title: 'ProfilMedecinUpdate'
} as const;

export const ProfilPatientCreateSchema = {
    properties: {
        date_naissance: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Naissance'
        },
        antecedents: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Antecedents'
        }
    },
    type: 'object',
    title: 'ProfilPatientCreate'
} as const;

export const ProfilPatientPublicSchema = {
    properties: {
        date_naissance: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Naissance'
        },
        antecedents: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Antecedents'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['id', 'user_id'],
    title: 'ProfilPatientPublic'
} as const;

export const StatutOrdonnanceSchema = {
    type: 'string',
    enum: ['brouillon', 'signee', 'preparee', 'dispensee', 'annulee'],
    title: 'StatutOrdonnance'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TypeAssetSchema = {
    type: 'string',
    enum: ['signature', 'cachet'],
    title: 'TypeAsset'
} as const;

export const TypeUtilisateurSchema = {
    type: 'string',
    enum: ['medecin', 'patient', 'pharmacien'],
    title: 'TypeUtilisateur'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        type_utilisateur: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TypeUtilisateur'
                },
                {
                    type: 'null'
                }
            ]
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        type_utilisateur: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TypeUtilisateur'
                },
                {
                    type: 'null'
                }
            ]
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        type_utilisateur: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TypeUtilisateur'
                },
                {
                    type: 'null'
                }
            ]
        },
        numero_ordre: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Numero Ordre'
        },
        specialite: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specialite'
        },
        pays_exercice: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pays Exercice'
        },
        numero_licence: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Numero Licence'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;