// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, MedecinsReadMyProfilResponse, MedecinsCreateMyProfilData, MedecinsCreateMyProfilResponse, MedecinsUpdateMyProfilData, MedecinsUpdateMyProfilResponse, MedecinsUploadAssetData, MedecinsUploadAssetResponse, MedecinsListMyAssetsData, MedecinsListMyAssetsResponse, OrdonnancesReadOrdonnancesData, OrdonnancesReadOrdonnancesResponse, OrdonnancesCreateOrdonnanceData, OrdonnancesCreateOrdonnanceResponse, OrdonnancesReadOrdonnanceData, OrdonnancesReadOrdonnanceResponse, OrdonnancesGenerateOrdonnanceData, OrdonnancesGenerateOrdonnanceResponse, PatientsReadMyPatientProfilResponse, PatientsCreateMyPatientProfilData, PatientsCreateMyPatientProfilResponse, PatientsCreateGhostPatientProfilData, PatientsCreateGhostPatientProfilResponse, PatientsSearchPatientsData, PatientsSearchPatientsResponse, PrivateCreateUserData, PrivateCreateUserResponse, TemplatesListMyTemplatesResponse, TemplatesUploadTemplateData, TemplatesUploadTemplateResponse, TemplatesDeleteTemplateData, TemplatesDeleteTemplateResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class MedecinsService {
    /**
     * Read My Profil
     * Récupérer le profil médecin de l'utilisateur connecté.
     * @returns ProfilMedecinPublic Successful Response
     * @throws ApiError
     */
    public static readMyProfil(): CancelablePromise<MedecinsReadMyProfilResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/medecins/me'
        });
    }
    
    /**
     * Create My Profil
     * Créer le profil médecin pour l'utilisateur connecté.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProfilMedecinPublic Successful Response
     * @throws ApiError
     */
    public static createMyProfil(data: MedecinsCreateMyProfilData): CancelablePromise<MedecinsCreateMyProfilResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/medecins/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update My Profil
     * Mettre à jour le profil médecin de l'utilisateur connecté.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProfilMedecinPublic Successful Response
     * @throws ApiError
     */
    public static updateMyProfil(data: MedecinsUpdateMyProfilData): CancelablePromise<MedecinsUpdateMyProfilResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/medecins/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Upload Asset
     * Uploader une image de signature ou de cachet pour le médecin connecté.
     * @param data The data for the request.
     * @param data.formData
     * @returns AssetMedecinPublic Successful Response
     * @throws ApiError
     */
    public static uploadAsset(data: MedecinsUploadAssetData): CancelablePromise<MedecinsUploadAssetResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/medecins/me/assets',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List My Assets
     * Lister les signatures et cachets récents uploadés par le médecin connecté.
     * @param data The data for the request.
     * @param data.typeAsset
     * @returns AssetMedecinPublic Successful Response
     * @throws ApiError
     */
    public static listMyAssets(data: MedecinsListMyAssetsData = {}): CancelablePromise<MedecinsListMyAssetsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/medecins/me/assets',
            query: {
                type_asset: data.typeAsset
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class OrdonnancesService {
    /**
     * Read Ordonnances
     * Récupérer les ordonnances du médecin connecté (ou toutes si superuser).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns OrdonnancesPublic Successful Response
     * @throws ApiError
     */
    public static readOrdonnances(data: OrdonnancesReadOrdonnancesData = {}): CancelablePromise<OrdonnancesReadOrdonnancesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/ordonnances/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Ordonnance
     * Créer une nouvelle ordonnance.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns OrdonnancePublic Successful Response
     * @throws ApiError
     */
    public static createOrdonnance(data: OrdonnancesCreateOrdonnanceData): CancelablePromise<OrdonnancesCreateOrdonnanceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/ordonnances/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Ordonnance
     * Récupérer une ordonnance par son ID.
     * @param data The data for the request.
     * @param data.id
     * @returns OrdonnancePublic Successful Response
     * @throws ApiError
     */
    public static readOrdonnance(data: OrdonnancesReadOrdonnanceData): CancelablePromise<OrdonnancesReadOrdonnanceResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/ordonnances/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Generate Ordonnance
     * Génère un PDF à partir de contenu HTML, remplace les tokens, le sauvegarde et crée l'ordonnance.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns OrdonnancePublic Successful Response
     * @throws ApiError
     */
    public static generateOrdonnance(data: OrdonnancesGenerateOrdonnanceData): CancelablePromise<OrdonnancesGenerateOrdonnanceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/ordonnances/generate',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PatientsService {
    /**
     * Read My Patient Profil
     * Récupérer le profil patient de l'utilisateur connecté.
     * @returns ProfilPatientPublic Successful Response
     * @throws ApiError
     */
    public static readMyPatientProfil(): CancelablePromise<PatientsReadMyPatientProfilResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/patients/me'
        });
    }
    
    /**
     * Create My Patient Profil
     * Créer le profil patient pour l'utilisateur connecté.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProfilPatientPublic Successful Response
     * @throws ApiError
     */
    public static createMyPatientProfil(data: PatientsCreateMyPatientProfilData): CancelablePromise<PatientsCreateMyPatientProfilResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/patients/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Ghost Patient Profil
     * Créer un profil patient 'fantôme' (non encore inscrit) par un médecin pour une consultation.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProfilPatientPublic Successful Response
     * @throws ApiError
     */
    public static createGhostPatientProfil(data: PatientsCreateGhostPatientProfilData): CancelablePromise<PatientsCreateGhostPatientProfilResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/patients/fantome',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Search Patients
     * Lister ou rechercher des patients (réservé exclusivement aux médecins authentifiés).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ProfilPatientPublic Successful Response
     * @throws ApiError
     */
    public static searchPatients(data: PatientsSearchPatientsData = {}): CancelablePromise<PatientsSearchPatientsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/patients/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class TemplatesService {
    /**
     * List My Templates
     * Lister tous les modèles d'ordonnances (.docx) enregistrés par le médecin connecté.
     * @returns OrdonnanceTemplatePublic Successful Response
     * @throws ApiError
     */
    public static listMyTemplates(): CancelablePromise<TemplatesListMyTemplatesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/templates/'
        });
    }
    
    /**
     * Upload Template
     * Uploader un fichier modèle .docx et détecter automatiquement les tokens ($patient$, $signature:img$, etc.)
     * @param data The data for the request.
     * @param data.formData
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static uploadTemplate(data: TemplatesUploadTemplateData): CancelablePromise<TemplatesUploadTemplateResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/templates/upload',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Template
     * Supprimer un modèle d'ordonnance.
     * @param data The data for the request.
     * @param data.id
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteTemplate(data: TemplatesDeleteTemplateData): CancelablePromise<TemplatesDeleteTemplateResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/templates/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}