// This file is auto-generated by @hey-api/openapi-ts

export type AssetMedecinPublic = {
    type_asset: TypeAsset;
    chemin_fichier: string;
    est_par_defaut?: boolean;
    id: string;
    medecin_id: string;
    created_at?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_medecins_upload_asset = {
    type_asset: TypeAsset;
    file: string;
    est_par_defaut?: boolean;
};

export type Body_templates_upload_template = {
    nom_template: string;
    file: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrdonnanceCreate = {
    patient_id: string;
    template_id: string;
};

export type OrdonnanceGenerateRequest = {
    html_content: string;
    patient_id: string;
    template_id: string;
    paper_size?: string;
};

export type OrdonnancePublic = {
    pdf_name?: (string | null);
    docx_name?: (string | null);
    statut?: StatutOrdonnance;
    id: string;
    medecin_id: string;
    patient_id: string;
    template_id: string;
    date_emission?: (string | null);
    date_signature?: (string | null);
    lien_token: string;
};

export type OrdonnancesPublic = {
    data: Array<OrdonnancePublic>;
    count: number;
};

export type OrdonnanceTemplatePublic = {
    nom_template: string;
    chemin_fichier_docx: string;
    id: string;
    medecin_id: string;
    date_upload?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProfilMedecinCreate = {
    numero_ordre: string;
    specialite: string;
    pays_exercice: string;
    bio?: (string | null);
    est_verifie?: boolean;
};

export type ProfilMedecinPublic = {
    numero_ordre: string;
    specialite: string;
    pays_exercice: string;
    bio?: (string | null);
    est_verifie?: boolean;
    id: string;
    user_id: string;
};

export type ProfilMedecinUpdate = {
    specialite?: (string | null);
    bio?: (string | null);
    est_verifie?: (boolean | null);
};

export type ProfilPatientCreate = {
    date_naissance?: (string | null);
    antecedents?: (string | null);
};

export type ProfilPatientPublic = {
    date_naissance?: (string | null);
    antecedents?: (string | null);
    id: string;
    user_id: (string | null);
};

export type StatutOrdonnance = 'brouillon' | 'signee' | 'preparee' | 'dispensee' | 'annulee';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TypeAsset = 'signature' | 'cachet';

export type TypeUtilisateur = 'medecin' | 'patient' | 'pharmacien';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    type_utilisateur?: (TypeUtilisateur | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    type_utilisateur?: (TypeUtilisateur | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    type_utilisateur?: (TypeUtilisateur | null);
    numero_ordre?: (string | null);
    specialite?: (string | null);
    pays_exercice?: (string | null);
    numero_licence?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MedecinsReadMyProfilResponse = (ProfilMedecinPublic);

export type MedecinsCreateMyProfilData = {
    requestBody: ProfilMedecinCreate;
};

export type MedecinsCreateMyProfilResponse = (ProfilMedecinPublic);

export type MedecinsUpdateMyProfilData = {
    requestBody: ProfilMedecinUpdate;
};

export type MedecinsUpdateMyProfilResponse = (ProfilMedecinPublic);

export type MedecinsUploadAssetData = {
    formData: Body_medecins_upload_asset;
};

export type MedecinsUploadAssetResponse = (AssetMedecinPublic);

export type MedecinsListMyAssetsData = {
    typeAsset?: (TypeAsset | null);
};

export type MedecinsListMyAssetsResponse = (Array<AssetMedecinPublic>);

export type OrdonnancesReadOrdonnancesData = {
    limit?: number;
    skip?: number;
};

export type OrdonnancesReadOrdonnancesResponse = (OrdonnancesPublic);

export type OrdonnancesCreateOrdonnanceData = {
    requestBody: OrdonnanceCreate;
};

export type OrdonnancesCreateOrdonnanceResponse = (OrdonnancePublic);

export type OrdonnancesReadOrdonnanceData = {
    id: string;
};

export type OrdonnancesReadOrdonnanceResponse = (OrdonnancePublic);

export type OrdonnancesGenerateOrdonnanceData = {
    requestBody: OrdonnanceGenerateRequest;
};

export type OrdonnancesGenerateOrdonnanceResponse = (OrdonnancePublic);

export type PatientsReadMyPatientProfilResponse = (ProfilPatientPublic);

export type PatientsCreateMyPatientProfilData = {
    requestBody: ProfilPatientCreate;
};

export type PatientsCreateMyPatientProfilResponse = (ProfilPatientPublic);

export type PatientsCreateGhostPatientProfilData = {
    requestBody: ProfilPatientCreate;
};

export type PatientsCreateGhostPatientProfilResponse = (ProfilPatientPublic);

export type PatientsSearchPatientsData = {
    limit?: number;
    skip?: number;
};

export type PatientsSearchPatientsResponse = (Array<ProfilPatientPublic>);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TemplatesListMyTemplatesResponse = (Array<OrdonnanceTemplatePublic>);

export type TemplatesUploadTemplateData = {
    formData: Body_templates_upload_template;
};

export type TemplatesUploadTemplateResponse = ({
    [key: string]: unknown;
});

export type TemplatesDeleteTemplateData = {
    id: string;
};

export type TemplatesDeleteTemplateResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);