"""schema initial odimed

Revision ID: 768ea0eebfe1
Revises: fe56fa70289e
Create Date: 2026-08-03 10:43:25.523486

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '768ea0eebfe1'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('code_cim10', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_code_cim10'), 'diagnostic', ['code_cim10'], unique=False)
    op.create_table('molecule',
    sa.Column('nom_molecule', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_molecule_nom_molecule'), 'molecule', ['nom_molecule'], unique=True)
    op.create_table('officine',
    sa.Column('nom_officine', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('adresse', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gardeofficine',
    sa.Column('debut_garde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin_garde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('officine_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('fin_garde > debut_garde', name='ck_gardeofficine_fin_apres_debut'),
    sa.ForeignKeyConstraint(['officine_id'], ['officine.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicament',
    sa.Column('nom_officiel', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('forme', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('dosage', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('molecule_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['molecule_id'], ['molecule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicament_nom_officiel'), 'medicament', ['nom_officiel'], unique=False)
    op.create_table('profilmedecin',
    sa.Column('numero_ordre', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('specialite', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('pays_exercice', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('est_verifie', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profilmedecin_numero_ordre'), 'profilmedecin', ['numero_ordre'], unique=True)
    op.create_table('profilpatient',
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('antecedents', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profilpharmacien',
    sa.Column('numero_licence', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('est_verifie', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('officine_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['officine_id'], ['officine.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profilpharmacien_numero_licence'), 'profilpharmacien', ['numero_licence'], unique=True)
    op.create_table('assetmedecin',
    sa.Column('type_asset', sa.Enum('signature', 'cachet', name='typeasset'), nullable=False),
    sa.Column('chemin_fichier', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('est_par_defaut', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('medecin_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medecin_id'], ['profilmedecin.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicamentdiagnostic',
    sa.Column('medicament_id', sa.Uuid(), nullable=False),
    sa.Column('diagnostic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicament_id'], ['medicament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medicament_id', 'diagnostic_id')
    )
    op.create_table('ordonnancetemplate',
    sa.Column('nom_template', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('chemin_fichier_docx', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('medecin_id', sa.Uuid(), nullable=False),
    sa.Column('date_upload', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medecin_id'], ['profilmedecin.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordonnance',
    sa.Column('pdf_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('docx_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('statut', sa.Enum('brouillon', 'signee', 'preparee', 'dispensee', 'annulee', name='statutordonnance'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('medecin_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('date_emission', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_signature', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lien_token', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['profilmedecin.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['profilpatient.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['ordonnancetemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordonnance_lien_token'), 'ordonnance', ['lien_token'], unique=True)
    op.create_table('ordonnanceligne',
    sa.Column('posologie', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('duree_traitement', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ordonnance_id', sa.Uuid(), nullable=False),
    sa.Column('medicament_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['medicament_id'], ['medicament.id'], ),
    sa.ForeignKeyConstraint(['ordonnance_id'], ['ordonnance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    typeutilisateur_enum = postgresql.ENUM('medecin', 'patient', 'pharmacien', name='typeutilisateur')
    typeutilisateur_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('type_utilisateur', typeutilisateur_enum, nullable=True))
    op.create_index(op.f('ix_user_type_utilisateur'), 'user', ['type_utilisateur'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_type_utilisateur'), table_name='user')
    op.drop_column('user', 'type_utilisateur')
    postgresql.ENUM(name='typeutilisateur').drop(op.get_bind(), checkfirst=True)
    op.drop_table('ordonnanceligne')
    op.drop_index(op.f('ix_ordonnance_lien_token'), table_name='ordonnance')
    op.drop_table('ordonnance')
    op.drop_table('ordonnancetemplate')
    op.drop_table('medicamentdiagnostic')
    op.drop_table('assetmedecin')
    op.drop_index(op.f('ix_profilpharmacien_numero_licence'), table_name='profilpharmacien')
    op.drop_table('profilpharmacien')
    op.drop_table('profilpatient')
    op.drop_index(op.f('ix_profilmedecin_numero_ordre'), table_name='profilmedecin')
    op.drop_table('profilmedecin')
    op.drop_index(op.f('ix_medicament_nom_officiel'), table_name='medicament')
    op.drop_table('medicament')
    op.drop_table('gardeofficine')
    op.drop_table('officine')
    op.drop_index(op.f('ix_molecule_nom_molecule'), table_name='molecule')
    op.drop_table('molecule')
    op.drop_index(op.f('ix_diagnostic_code_cim10'), table_name='diagnostic')
    op.drop_table('diagnostic')
    # ### end Alembic commands ###
